import type { Metadata, Viewport } from "next";
import Script from "next/script";
import { GeistSans } from "geist/font/sans";
import { Instrument_Serif } from "next/font/google";
import localFont from "next/font/local";
import CursorSun from "@/components/cursor-sun";
import { MotionProvider } from "@/components/motion-provider";
import "./globals.css";

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
  variable: "--font-serif",
  display: "swap",
});

// Cabinet Grotesk — self-hosted display sans for headlines (Fontshare).
// Self-hosted in /public/fonts/ to avoid CDN latency + reliability risk.
// Only Medium (500) and Bold (700) — those are the weights we use for
// hero/h1/h2; loading more would just inflate the cold-start payload.
const cabinetGrotesk = localFont({
  src: [
    {
      path: "../public/fonts/CabinetGrotesk-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/CabinetGrotesk-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-display",
  display: "swap",
  // System fallbacks chosen for similar x-height and width so layout doesn't
  // shift visibly when the real font swaps in.
  fallback: ["ui-sans-serif", "system-ui", "-apple-system", "Segoe UI", "sans-serif"],
});

const SITE_URL = "https://daycraftstudio.com";
const SITE_TITLE = "Daycraft Studio — Websites for small businesses in North Jersey";
const SITE_DESCRIPTION =
  "Clean, fast, professional websites for small businesses. Starting at $350. Based in North Jersey. Booking June–July 2026.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: SITE_TITLE,
  description: SITE_DESCRIPTION,
  keywords: [
    "web design",
    "web designer",
    "North Jersey",
    "New Jersey",
    "small business websites",
    "freelance web designer",
    "affordable websites",
    "Passaic",
    "Rowan University",
  ],
  authors: [{ name: "Igor Melnyk" }],
  creator: "Igor Melnyk — Daycraft Studio",
  publisher: "Daycraft Studio",
  openGraph: {
    title: "Daycraft Studio",
    description:
      "Modern web design for small businesses in North Jersey. From $350.",
    url: SITE_URL,
    siteName: "Daycraft Studio",
    type: "website",
    locale: "en_US",
    // OG image is generated by app/opengraph-image.tsx (Next.js file
    // convention) — it injects og:image automatically, so no explicit
    // `images` array is needed here.
  },
  twitter: {
    card: "summary_large_image",
    title: "Daycraft Studio",
    description:
      "Modern web design for small businesses in North Jersey. From $350.",
  },
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    shortcut: "/favicon.svg",
    // apple-icon.svg lives at app/apple-icon.svg — Next.js serves it
    // automatically; explicit declaration not required.
  },
};

export const viewport: Viewport = {
  themeColor: "#FAF8F3",
  width: "device-width",
  initialScale: 1,
};

/**
 * Structured data — tells Google this is a real professional service so
 * the site is eligible for richer search-result treatment. Update fields
 * here (areaServed, priceRange, email) if the business model shifts.
 */
const structuredData = {
  "@context": "https://schema.org",
  "@type": "ProfessionalService",
  name: "Daycraft Studio",
  description: "Web design for small businesses in North Jersey",
  url: SITE_URL,
  telephone: "+1-201-771-0092",
  email: "hello@daycraftstudio.com",
  founder: {
    "@type": "Person",
    name: "Igor Melnyk",
  },
  address: {
    "@type": "PostalAddress",
    addressRegion: "NJ",
    addressCountry: "US",
  },
  areaServed: "New Jersey",
  priceRange: "$350–$1,200+",
  knowsAbout: [
    "Web design",
    "Next.js",
    "Small business websites",
    "Mobile-first design",
  ],
  image: `${SITE_URL}/og-image.png`,
  logo: `${SITE_URL}/favicon.svg`,
  sameAs: ["https://instagram.com/daycraft.studio"],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${instrumentSerif.variable} ${cabinetGrotesk.variable}`}
    >
      <body className="font-sans bg-cream text-charcoal antialiased relative">
        {/* Content sits above the grain overlay (z-1 in globals.css).
            MotionProvider makes all Framer Motion respect prefers-reduced-motion. */}
        <div className="relative z-10">
          <MotionProvider>{children}</MotionProvider>
        </div>

        {/* Easter egg: soft sun glow trailing the cursor on hover devices. */}
        <CursorSun />

        {/* Structured data for search engines. */}
        <Script
          id="ld-json-org"
          type="application/ld+json"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />

        {/* Easter egg: a tiny hello to anyone who opens devtools. */}
        <Script id="console-hello" strategy="afterInteractive">
          {`
            try {
              console.log(
                "%cDaycraft Studio %c· crafted before the sun comes up\\n%cWant a site like this? hello@daycraftstudio.com",
                "color:#1A1A1A;font-weight:600;font-size:14px;",
                "color:#6B8CAE;font-style:italic;font-size:13px;",
                "color:#666;font-size:12px;"
              );
            } catch (e) {}
          `}
        </Script>
      </body>
    </html>
  );
}
